# Generated by Django 5.1.4 on 2025-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
