# Generated by Django 5.1.5 on 2025-01-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
